spring.application.name=SpringOauth
server.port=8085


#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=

spring.security.oauth2.client.registration.github.client-id=Ov23liMb6OTmbHpwXYwZ
spring.security.oauth2.client.registration.github.client-secret=fdb0764bde3d535d4a335d268cc08f9dd8e62d9d

